language: python
python:
    - "2.6"
    - "2.7"

notifications:
  email:
    - hanno@hannosch.eu
    - pycassa.maintainer@gmail.com

before_install:
    - test -f "/usr/local/cassandra/etc/cassandra-env.sh" && sudo rm -f /usr/local/cassandra/conf/cassandra-env.sh && sudo ln -s /usr/local/cassandra/etc/cassandra-env.sh /usr/local/cassandra/conf/cassandra-env.sh
    - sudo service cassandra start
    - sleep 3

install:
    - python setup.py develop

script:
    - nosetests -v
