language: python
python:
    - "2.5"
    - "2.6"
    - "2.7"

notifications:
  email:
    - hanno@hannosch.eu
    - pycassa.maintainer@gmail.com

before_install:
    - sudo service cassandra start
    - sleep 3
    - sudo service cassandra status

install:
    - python setup.py develop

script:
    - nosetests -v
