language: python
python:
    - "2.6"
    - "2.7"

notifications:
  email:
    - hanno@hannosch.eu
    - pycassa.maintainer@gmail.com

before_install:
    - sudo apt-get install libjna-java
    - sudo ln -s /usr/share/java/jna.jar /usr/local/cassandra/lib/
    - sudo service cassandra start
    - sleep 3
    - sudo service cassandra status

install:
    - python setup.py develop

script:
    - nosetests -v
